### ISSUE TITLE
Battle.net OAuth2 token expires

### ISSUE THREAD

**Issue by pugglesongit** [Mast3rwaf1z/nutbot#102]
Nut bot having an issue with invoking. Code string " Cannot invoke "org.json.JSONObject.getJSONObject(String)" because "data" is null" only affecting the raid application from what I can see as that's where the message was.

**Comment by Mast3rwaf1z** [comment]
The OAuth2 token from the battle.net servers needs to be verified before use, if it has been expired, regenerate it
